version: '3.3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - 5500:5500
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file: .env.postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
